version: "3.4"

services:
  db:
    image: postgres:13-alpine
    restart: always
    container_name: pasha-db
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - db-data:/var/lib/postgresql/data-pasha-db:rw
    ports:
      - "5432:5432"

volumes:
  db-data: {}

